# Generated by Django 4.2.7 on 2026-01-10 19:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('customer_type', models.CharField(choices=[('regular', 'Обычный'), ('loyalty', 'Участник программы лояльности'), ('corporate', 'Корпоративный')], default='regular', max_length=20, verbose_name='Тип клиента')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('tier', models.CharField(choices=[('bronze', 'Бронзовый'), ('silver', 'Серебряный'), ('gold', 'Золотой')], default='bronze', max_length=20, verbose_name='Уровень')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Программа лояльности',
                'verbose_name_plural': 'Программы лояльности',
            },
        ),
    ]
