# Generated by Django 4.2.7 on 2026-01-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('unit', models.CharField(choices=[('kg', 'Килограмм'), ('g', 'Грамм'), ('l', 'Литр'), ('ml', 'Миллилитр'), ('pcs', 'Штуки')], max_length=10, verbose_name='Единица измерения')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущий запас')),
                ('min_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальный запас')),
                ('max_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальный запас')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за единицу')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient', verbose_name='Ингредиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ингредиент продукта',
                'verbose_name_plural': 'Ингредиенты продуктов',
                'unique_together': {('product', 'ingredient')},
            },
        ),
    ]
